version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"  # Adjust if package.json is in a subfolder
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "npm"
